---
helm:
  params:
    controller.status.processors: 20
    controller.operation.processors: 10
    controller.self.heal.timeout.seconds: 5
    controller.repo.server.timeout.seconds: 60

  controller:
    name: application-controller
    replicas: 2
    enableStatefulSet: false
    readinessProbe:
      failureThreshold: 3,
      initialDelaySeconds: 10,
      periodSeconds: 10,
      successThreshold: 1
      timeoutSeconds: 1
      livenessProbe:
    logFormat: json
    logLevel: info